### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by ricky-sb** [Citizenship-Portal/Nuxt-Demo#1]
Let's set up CI/CD to auto-deploy to GitHub Pages. We should also have the pipeline run our Jest tests on each commit, and run it through https://pa11y.org/ as well.

**Comment by ricky-sb** [comment]
Link here: https://github.com/Citizenship-Portal/Nuxt-Demo/  

Let's add all this to the docs.

**Comment by kayyali18** [comment]
Are we good to close this?

**Comment by ricky-sb** [comment]
I still need to set it up to run tests/accessibility
