### ISSUE TITLE
Configure ESLint & Prettier

### ISSUE THREAD

**Issue by kayyali18** [Citizenship-Portal/Nuxt-Demo#2]
Universal linting and prettier configurations will help keep all of us smiling and on the same page
Code is art, so let's make it look good

`.eslintrc.js` & `.prettierrc` files need a "Quarantine Haircut"

**Comment by ricky-sb** [comment]
Let's use [Airbnb's config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

**Comment by amcdevitt97** [comment]
Committed to master instead of making a branch, sorry about that. Next time I'll be PR-ing branches related to this project. Good to close this issue?

**Comment by kayyali18** [comment]
Thanks for the updates!
Try forking repos when doing Open Source contributions in the future, so if you push to master it'll be the fork

**Comment by kayyali18** [comment]
Also @amcdevitt97 please update the README to include you as a contributor
